dummy:
  gazebo_ros_control:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    pid_gains:
      joint1:   {p: 1000.0, i: 0.0, d: 0.0, i_clamp: 0.0}
      joint2:   {p: 1000.0, i: 0.0, d: 0.0, i_clamp: 0.0}
      joint3:   {p: 10.0, i: 0.0, d: 0.0, i_clamp: 0.0}
      joint4:   {p: 10.0, i: 0.0, d: 0.0, i_clamp: 0.0}
      joint5:   {p: 10.0, i: 0.0, d: 0.0, i_clamp: 0.0}
      joint6:   {p: 0.0, i: 0.0, d: 0.0, i_clamp: 0.0}

